# Generated by Django 3.1.2 on 2020-12-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
