# Generated by Django 3.1.2 on 2020-12-07 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0004_auto_20201207_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
