# Generated by Django 3.1.2 on 2020-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0005_auto_20201207_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='token',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
