# Generated by Django 3.1.2 on 2020-10-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20201009_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
