# Generated by Django 3.1.2 on 2020-10-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
    ]
